version: "3"
services:
  mysql:
    image: mysql
    container_name: compose-uebung03-mysql
    networks:
      - db-net
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=mydatabase
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 20
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: compose-uebung03-phpmyadmin
    ports:
      - 8080:80
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    networks:
      - db-net

networks:
  db-net:
    driver: "bridge"
